stages:
  - init
  - deploy

init:
  stage: init
  script:
    - npm cache clean
    - rm -rf node-modules
    - npm install

deploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/angular-deploy.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment:
  name: staging
  url: https://angular-mentoring-course-app.herokuapp.com/
  only:
    - master
